#!/usr/bin/php -q
<?php
        $dn = dirname(__FILE__);
        if ($dn == "/usr/bin") { $incf = "/etc/ssh2all.conf"; }
        else { $incf = "{$dn}/config.php"; }
        if (!file_exists($incf)) { die("ssh2all: config file not found: {$incf}\n"); }
        require_once($incf);

        if ($_SERVER["argc"] < 2) { printHelp(); }

        $flags = array("json" => false);
        $opt = $_SERVER["argv"][1];
        $cmdstart = 1;
        if (substr($opt, 0, 2) == "--") {
                switch ($opt) {
                        case "--json":
                                $flags["json"] = true;
                                $cmdstart++;
                                break;
                        default:
                                printHelp();
                                break;
                }
        }

        $cmd = "";
        for ($i = $cmdstart; $i < $_SERVER["argc"]; $i++) {
                $cmd = "{$cmd} {$_SERVER["argv"][$i]}";
        }

        $cmd = trim($cmd);

        if ($cmd == "") { printHelp(); }

        if (!$flags["json"]) {
                print "Running \"{$cmd}\" against ".count($hosts)." hosts...\n";
                print "\033[32mLast chance to abort. Starting in";
                for ($i = 3; $i > 0; $i--) {
                        print " \033[36m{$i}\033[0m";
                        sleep(1);
                }
                print "\033[0m\n";
        }

        $js = array();
        foreach ($hosts as $host) { execnode($host, $cmd); }

        if ($flags["json"]) {
                print json_encode($js, JSON_FORCE_OBJECT);
        }

        function execnode($node, $cmd) {
                global $creds;
                global $flags;
                global $js;
                if (!$flags["json"]) {
                        print "\n\033[32m-------------------------------\033[0m\n";
                        print "\033[32m EXECUTING ON: \033[36m{$node}\033[32m ...\033[0m\n";
                        print "\033[32m-------------------------------\n\n\033[37m";
                        passthru("/usr/bin/sshpass -p '{$creds["password"]}' ssh -q -oStrictHostKeyChecking=no {$creds["username"]}@{$node} {$cmd}");
                }
                else {
                        $js[$node] = exec("/usr/bin/sshpass -p '{$creds["password"]}' ssh -q -oStrictHostKeyChecking=no {$creds["username"]}@{$node} {$cmd}");
                }
        }

        function printHelp() {
                print "usage: {$_SERVER["argv"][0]} [--json] <command>\n";
                die();
        }

?>
